export const pagesRoutes = [
  ["v-744ccd44","/src/",{"title":"博客主页"},["/src/README.md"]],
  ["v-7d690631","/src/intro.html",{"title":"介绍页"},[":md"]],
  ["v-6c5c0573","/src/slides.html",{"title":"幻灯片页"},[":md"]],
  ["v-b334c830","/src/demo/",{"title":"主要功能与配置演示"},["/src/demo/README.md"]],
  ["v-7517aed9","/src/demo/disable.html",{"title":"布局与功能禁用"},[":md"]],
  ["v-3ba1c57c","/src/demo/encrypt.html",{"title":"密码加密的文章"},[":md"]],
  ["v-697c033c","/src/demo/markdown.html",{"title":"Markdown 展示"},[":md"]],
  ["v-71832e7c","/src/demo/page.html",{"title":"页面配置"},[":md"]],
  ["v-f3310c40","/src/posts/cherry.html",{"title":"樱桃"},[":md"]],
  ["v-5a220498","/src/posts/dragonfruit.html",{"title":"火龙果"},[":md"]],
  ["v-0521efea","/src/posts/strawberry.html",{"title":"草莓"},[":md"]],
  ["v-2c84ee0f","/src/posts/tomato.html",{"title":"番茄"},[":md"]],
  ["v-54c2c49d","/src/posts/apple/1.html",{"title":"苹果 1"},[":md"]],
  ["v-56779d3c","/src/posts/apple/2.html",{"title":"苹果 2"},[":md"]],
  ["v-582c75db","/src/posts/apple/3.html",{"title":"苹果 3"},[":md"]],
  ["v-59e14e7a","/src/posts/apple/4.html",{"title":"苹果 4"},[":md"]],
  ["v-2e3cf432","/src/posts/banana/1.html",{"title":"香蕉 1"},[":md"]],
  ["v-2ff1ccd1","/src/posts/banana/2.html",{"title":"香蕉 2"},[":md"]],
  ["v-31a6a570","/src/posts/banana/3.html",{"title":"香蕉 3"},[":md"]],
  ["v-335b7e0f","/src/posts/banana/4.html",{"title":"香蕉 4"},[":md"]],
  ["v-3706649a","/404.html",{"title":""},[]],
]
